uage: elixir
elixir:
  - 1.2.6
  - 1.3.2
otp_release:
  - 18.1
sudo: false # to use faster container based build environment

install:
  - mix local.rebar --force # for Elixir 1.3.0 and up
  - mix local.hex --force
  - mix deps.get
script:
  - mix test
