language: elixir
elixir:
  - 1.0.5
  - 1.1.1
  - 1.2.5
  - 1.3.4
otp_release:
  - 18.3
  - 19.0
install:
  - mix do local.hex --force, local.rebar --force
  - mix deps.get # need to explicitly get test deps, see mix.exs
  - mix compile
script:
  - mix test
matrix:
  exclude:
    - otp_release: 19.0
      elixir: 1.0.5
    - otp_release: 19.0
      elixir: 1.1.1
    - otp_release: 19.0
      elixir: 1.2.5