uage: elixir
elixir:
  - 1.2.6
  - 1.3.2
otp_release:
  - 18.1
sudo: false # to use faster container based build environment

install:
  - mix do local.hex --force, local.rebar --force
  - mix deps.get # need to explicitly get test deps, see mix.exs
  - mix compile
script:
  - mix test
